// docs/src/components/vue/AllTypesDemo.vue
<template>
  <inspect-value ref="el" name="types" />
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { allTypesData } from '../shared/demo-data';

const el = ref<HTMLElement | null>(null);

onMounted(async () => {
  await import('../../../../dist/inspect-value.js');
  if (!el.value) return;
  (el.value as any).value = allTypesData;
  (el.value as any).expandAll = true;
});
</script>

// docs/src/components/svelte/AllTypesDemo.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { allTypesData } from '../shared/demo-data';

  let el: HTMLElement | undefined = $state();

  onMount(async () => {
    await import('../../../../dist/inspect-value.js');
    if (!el) return;
    (el as any).value = allTypesData;
    (el as any).expandAll = true;
  });
</script>

<inspect-value bind:this={el} name="types" />
