// docs/src/components/vue/AllTypesDemo.vue
<template>
  <inspect-value ref="el" name="types" />
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { allTypesData } from '../shared/demo-data';

const el = ref<HTMLElement | null>(null);

onMounted(async () => {
  await import('../../../../dist/inspect-value.js');
  if (!el.value) return;
  (el.value as any).value = allTypesData;
  (el.value as any).expandAll = true;
});
</script>

// docs/src/components/react/AllTypesDemo.tsx
import { useRef, useEffect } from 'react';
import { allTypesData } from '../shared/demo-data';

export default function AllTypesDemo() {
  const ref = useRef<HTMLElement>(null);

  useEffect(() => {
    import('../../../../dist/inspect-value.js').then(() => {
      if (!ref.current) return;
      (ref.current as any).value = allTypesData;
      (ref.current as any).expandAll = true;
    });
  }, []);

  return <inspect-value ref={ref} name="types" />;
}
